version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run:
          name: Install CM
          command: |
            curl -s https://aerokube.com/cm/bash | bash
            ./cm selenoid start --vnc
      - run:
          name: Date
          command: date

workflows:
  main:
    jobs:
      - build-and-test
