version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run:
          command: python --version
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
