version: 2.1

orbs:
  python: circleci/python@3.7.5

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: python --version
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
