version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    executor: circleci/python@3.1.4
    steps:
      - checkout
      - run:
          command: python --version
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
